import MarkdownIt from "markdown-it";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Component, elements, Style, whenFirst, whenHover } from "../../../src";
import Document from "../Document";
import Layout from "../components/Layout";
import { createSidebarPages } from "../navigation";
import { homeHeroClass, homeSummaryClass, homeTitleClass, monoFont } from "../styles";

const pageDirectory = path.dirname(fileURLToPath(import.meta.url));
const readmePath = path.resolve(pageDirectory, "../../../README.md");

const markdown = new MarkdownIt({
	html: false,
	linkify: true,
});

const articleStyle = Style.Class("docs-home-article", {
	color: "$textBody",
	fontSize: "15px",
	lineHeight: 1.7,
	...elements("h1", {
		color: "$textBright",
		fontSize: "24px",
		fontWeight: 700,
		letterSpacing: "-0.01em",
		margin: "28px 0 12px",
		...whenFirst({ marginTop: "0" }),
	}),
	...elements("h2", {
		color: "$textPrimary",
		fontSize: "19px",
		fontWeight: 600,
		letterSpacing: "-0.01em",
		margin: "24px 0 10px",
	}),
	...elements("h3", {
		color: "$textBody",
		fontSize: "17px",
		fontWeight: 600,
		margin: "20px 0 8px",
	}),
	...elements("p", { margin: "0 0 12px" }),
	...elements("ul", { margin: "0 0 12px", paddingLeft: "20px" }),
	...elements("ol", { margin: "0 0 12px", paddingLeft: "20px" }),
	...elements("li", { margin: "0 0 4px" }),
	...elements("code", {
		...monoFont,
		background: "$bgSurface",
		border: "1px solid $borderCode",
		borderRadius: "4px",
		color: "$accentPrimary",
		fontSize: "13px",
		padding: "2px 5px",
	}),
	...elements("pre", {
		background: "$bgCodeBlock",
		border: "1px solid $borderSubtle",
		borderRadius: "8px",
		margin: "0 0 16px",
		overflowX: "auto",
		padding: "16px",
		...elements("code", {
			background: "none",
			border: "none",
			color: "$textBody",
			fontSize: "14px",
			padding: "0",
		}),
	}),
	...elements("a", {
		color: "$accentPrimary",
		textDecoration: "none",
		...whenHover({ textDecoration: "underline" }),
	}),
	...elements("strong", { color: "$textPrimary" }),
});

export default Document(async (doc, project, path) => {
	doc.setTitle("kitsui");
	const readmeHtml = markdown.render(await readFile(readmePath, "utf8"));

	return Layout((content) => {
		const article = Component("article");
		article.class.add(articleStyle);
		article.element.innerHTML = readmeHtml;

		content.append(
			Component("section")
				.class.add(homeHeroClass)
				.append(
					Component("h1")
						.class.add(homeTitleClass)
						.text.set("kitsui"),
					Component("p")
						.class.add(homeSummaryClass)
						.text.set("A DOM-first UI library built around owned components and reactive state. These docs are generated by kitsui itself."),
				),
			article,
		);
	}, path, createSidebarPages(project));
});
